[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -Os
lib_deps =
    ESP Async WebServer@^1.2.3
    ArduinoJson@^7.0.0
    bblanchon/AsyncTCP@^1.1.1
    bblanchon/Preferences@^1.0.0
    https://github.com/br3ttb/Arduino-PID-Library.git
